#!/usr/bin/env sh
wget -O- https://raw.githubusercontent.com/aliyun-node/tnvm/master/install.sh | bash
export METHOD=script
source ~/.bash_profile
source ~/.bashrc
source ~/.zshrc


tnvm install node-v9.9.0
tnvm use node-v9.9.0


